### ISSUE TITLE
Research on Related Concepts and Technologies

### ISSUE THREAD

**Issue by ffvv0123** [Goboolean/auth-server#2]
### Description
- Auth-Server 관련 정보 서칭
- SSO, OAuth 2.0 등의 인증 기술의 장단점, 어떤 상황에서 사용할지 등을 공부
- Google, Github 로그인 및 회원가입을 사용하는 실제 서비스들이 어떻게 작동하는지 공부

### Task
- [ ] Summarize the OAuth 2.0 protocol
- [ ] Research the concept and examples of SSO
- [ ] Investigate the workings of Google SSO and Github SSO
